apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: "rabbitmq"
  USERS_API_URL: "http://users-service"
  GAMES_API_URL: "http://games-service"