apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: fcg
type: Opaque
stringData:
  CONNECTION_STRING: "Server=fcg-games.c1k0ou644rxp.sa-east-1.rds.amazonaws.com;Database=paymentsdb;User Id=postgres;Password=administrator;"
