name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: payments-api
  EKS_CLUSTER_NAME: fiap-eks-cluster
  K8S_DEPLOYMENT_NAME: payments-api
  K8S_NAMESPACE: fcg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build da imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY:latest ./Payments.Api/Payments.Api
          docker tag $ECR_REPOSITORY:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push para ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Atualizar kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

      - name: Aplicar manifests Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Atualizar imagem do Deployment
        run: |
          kubectl set image deployment/$K8S_DEPLOYMENT_NAME \
          $K8S_DEPLOYMENT_NAME=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest \
          -n $K8S_NAMESPACE

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/$K8S_DEPLOYMENT_NAME -n $K8S_NAMESPACE